In [29]:
import numpy as np

#Iterating through a Vector
arr = np.array([1,2,3])

for x in arr:
    print(x)
        

1
2
3


In [37]:
import numpy as np

#Iterating through a Matrix
arr = np.array([[1,2,3], [4,5,6]])

for x in arr:
    print(x)
print()

#Iterating through each scalar element in the 2D matrix
for x in arr:
    for y in x:
        print(y)

[1 2 3]
[4 5 6]

1
2
3
4
5
6



In [7]:
import numpy as np

#Iterating through Tensors
arr = ([[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]])

for x in arr:
    print(x)
    for y in x:
        print(y)
        for z in y: 
            print(z)
    print()

[[1, 2, 3], [4, 5, 6]]
[1, 2, 3]
1
2
3
[4, 5, 6]
4
5
6

[[1, 2, 3], [4, 5, 6]]
[1, 2, 3]
1
2
3
[4, 5, 6]
4
5
6



In [1]:
import numpy as np

#using nditer for iterations
arr = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])

for x in np.nditer(arr):
    print(x)
print()

#simultaneously changing datatypes (Type Casting)
arr2 = np.array([1,2,3,4,5])

for x in np.nditer(arr2, flags=["buffered"], op_dtypes=["S"]):
    print(x)

1
2
3
4
5
6
7
8

b'1'
b'2'
b'3'
b'4'
b'5'


In [19]:
import numpy as np

#Step-wise iteration
arr = np.array([[1,2,3], [4,5,6]])

for x in np.nditer(arr[:, ::2]):
    print(x)

1
3
4
6


In [29]:
import numpy as np

#Enumeration through a 1D array
arr = np.array([1,2,3,4,5])

for idx, val in np.ndenumerate(arr):
    print(idx, val)
print()

#Enumeration through a 2D array
arr2 = np.array([[1,2,3,4], [5,6,7,8]])

for idx, val in np.ndenumerate(arr2):
    print(idx, val)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [159]:
import numpy as np

#More practice
arr = np.arange(6).reshape(2,3)
print(arr)
print()
print(arr.T) #This is transposition. Swaps the r and c.
print()

#Enumeration
for idx, val in np.ndenumerate(arr):
    print(idx, val)
print()

#Type Casting
for x in np.nditer(arr, flags = ["buffered"], op_dtypes = "float"):
    print(x)
print()

for x in np.nditer(arr.T.copy(order = 'C')):
    print(x, end = ' ')

[[0 1 2]
 [3 4 5]]

[[0 3]
 [1 4]
 [2 5]]

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5

0.0
1.0
2.0
3.0
4.0
5.0

0 3 1 4 2 5 

In [93]:
#Broadcasting arrays
import numpy as np

a = np.arange(3)
b = np.arange(6).reshape(2,3)

for x,y in np.nditer([a,b]):
    print(f"{x}:{y}", end = " ")
print()
print()

arr = np.arange(6).reshape(1,2,3)
arr2 = np.arange(12).reshape(4,1,3)
print(arr, "\n\n", arr2)
print()

for x,y in np.nditer([arr,arr2]):
    print(f"{x}:{y}", end = " ")

0:0 1:1 2:2 0:3 1:4 2:5 

[[[0 1 2]
  [3 4 5]]] 

 [[[ 0  1  2]]

 [[ 3  4  5]]

 [[ 6  7  8]]

 [[ 9 10 11]]]

0:0 1:1 2:2 3:0 4:1 5:2 0:3 1:4 2:5 3:3 4:4 5:5 0:6 1:7 2:8 3:6 4:7 5:8 0:9 1:10 2:11 3:9 4:10 5:11 

In [168]:
import numpy as np
a = np.empty([3,3], dtype=int)
print(a)

with np.nditer(a, op_flags = ["writeonly"]) as anything:
    for i,x in enumerate(anything):
        x[...] = i*i
        print(f"{x}:{i}", end = " ")
        

[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]


In [224]:
import numpy as np

a = np.arange(12).reshape(4,1,3)
for row in np.nditer(a, flags=["external_loop"]):
    print(row)
    print(np.sum(row), end = " ")

[ 0  1  2  3  4  5  6  7  8  9 10 11]
66 

In [220]:
import numpy as np
a = np.arange(12).reshape(4,1,3)
for row in np.nditer(a):
    print(row, end = " ")
    print(np.sum(row), end = " ")

0 0 1 1 2 2 3 3 4 4 5 5 6 6 7 7 8 8 9 9 10 10 11 11 

In [232]:
import numpy as np
a = np.arange(3)
b = np.arange(8).reshape(2,4)
it = np.nditer([a,b,None], flags=["external_loop"], op_axes=[[0,-1,-1], [-1,0,1], None])
with it:
    for x,y,z in it:
        z[...] = x*y
    result = it.operands[2]
    
result

array([[[ 0,  0,  0,  0],
        [ 0,  0,  0,  0]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 0,  2,  4,  6],
        [ 8, 10, 12, 14]]])

In [278]:
#Reduction
import numpy as np

a = np.arange(24).reshape(2,3,4)
b = np.array(0)

with np.nditer([a,b], flags=["reduce_ok"], op_flags=["readwrite"]) as it:
    for x,y in it:
        y[...] += x
b

array(276)