In [25]:
import numpy as np

#Slicing and modifying arrays
arr = np.ones([5,5])
print(arr)
print()

arr2 = arr[1:4, 1:4]
arr2 = np.zeros([3,3])
arr2[1,1] = 9
print(arr2)
print()

arr[1:4, 1:4] = arr2
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [49]:
import numpy as np

#Indexing elements
arr = np.arange(1, 37)
arr = arr.reshape(6, 6)
print(arr)
print()

arr1 = arr[[0,1,2,3,4,5], [0,1,2,3,4,5]]
print(arr1)
print()

arr2 = arr[1:4, 2:5]
print(arr2)
print()

arr3 = arr[1:4, [1,3,4,5]]
print(arr3)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

[ 1  8 15 22 29 36]

[[ 9 10 11]
 [15 16 17]
 [21 22 23]]

[[ 8 10 11 12]
 [14 16 17 18]
 [20 22 23 24]]
