In [3]:
#This is a random test I found on the internet. I will attempt it off the bat with the knowledge I have on numPy then correct it later.

#import libraries using an alias
import numpy as np 

#creating a (6, 5) array running from one through thirty row-wise (default)
a = np.arange(1, 31).reshape(6, 5)
print(a)

#slicing the arrays according to test instructions
#TEST ONE
print(a[2:4, 0:2])

#TEST TWO
#print(a[1:0, 2:1, 3:2, 4:3]) => this is my first attempt but you can't index a 2d array 4 times so it's incorrect
#at this point I am stuck so I'll skip to the solution
print(a[[0,1,2,3], [1,2,3,4]]) #we use two different lists, so that numpy reads it as 2d indexing

#TEST THREE
#print(a[[0, 4, 5], [3,4]]) => numpy expects both index arrays to be the same shape. List one has three, list two has two.
#to correct that
print(a[[0,4,5], 3:])

#another solution to the similar test would be to use np.ix_ which I learnt after some interaction with AI.
rows = [0,4,5]
cols = [3, 4]
print(a[np.ix_(rows, cols)])

#I'll attempt to use np.ix_ on the second test
rows = [0,1,2,3]
cols = [1,2,3,4]
print(a[np.ix_(rows, cols)]) #this doesn't give the preferred solution. However, it's a revelation on how to use np.ix_


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
[[11 12]
 [16 17]]
[ 2  8 14 20]
[[ 4  5]
 [24 25]
 [29 30]]
[[ 4  5]
 [24 25]
 [29 30]]
[[ 2  3  4  5]
 [ 7  8  9 10]
 [12 13 14 15]
 [17 18 19 20]]
