In [29]:
#Using w3 schools alongside chatgpt for tutorials. "Leraning by reading", "Learning by Examples", "Learning by Exercises"
#I'll be robotic in my approach

#importing numpy and creating an array
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [117]:
#Dimensions in arrays

a = np.array(42) #0D array/Scalars
b = np.array([1,2,3,4]) #1D array/Vectors
c = np.array([[1,2,3,4], [5,6,7,8]]) #2D array/Matrix
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3], [4,5,6]]]) #3D array/Tensor

print(a) 
print(b)
print(c)
print(d)

#Ascertain the number of dimensions
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

#Creating higher dimensional arrays
arr = np.array([[1,2,3],[4,5,6]], ndmin = 5)
print(arr)
print("Array has", arr.ndim, "dimensions")
print(arr.shape)

#random test try-out
#Changing datatypes

#Convert into a unistring
syntax = np.array([1,2,3,4], dtype = "U")
print(syntax)
print(syntax.dtype)

#Convert into a string
syntax2 = np.array([5,6,7,8])
syntax2 = syntax2.astype(str)
print(syntax2) #the output does not correspond with the quizz' answer
print(syntax2.dtype)


42
[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
0
1
2
3
[[[[[1 2 3]
    [4 5 6]]]]]
Array has 5 dimensions
(1, 1, 1, 2, 3)
['1' '2' '3' '4']
<U1
['5' '6' '7' '8']
<U11


In [161]:
#Creating a range of numbers (stepwise)
#Use .arange(start, end, step)
rangeNum = np.arange(0, 21, 2)
print(rangeNum)

#Use .linspace(start, end, number of values)
rangeNum2 = np.linspace(0, 50, 3, dtype = int)
print(rangeNum2)

#More examples
#Example
rangeNum3 = np.arange(0, 51, 5)
print(rangeNum3)

#Example
rangeNum4 = np.linspace(0, 10, 5)
print(rangeNum4)

[ 0  2  4  6  8 10 12 14 16 18 20]
[ 0 25 50]
[ 0  5 10 15 20 25 30 35 40 45 50]
[ 0.   2.5  5.   7.5 10. ]
