In [19]:
from numpy import random
x = random.choice([3,5,7], p=[0.1,0.9,0.0], size=(3,5))
print(x)

y = random.choice([3,5,7,9], p=[0.1,0.3,0.5,0.1], size=(100))
print(y)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 3 3 5 5]]
[7 7 7 9 3 3 7 7 7 7 7 7 5 5 7 9 7 3 7 7 5 7 3 7 9 5 5 7 5 3 7 5 3 5 7 7 5
 7 3 5 7 7 5 7 7 5 3 7 7 5 3 3 7 9 7 7 7 5 7 3 7 5 9 7 7 9 7 7 5 9 7 7 3 7
 5 7 3 7 5 7 9 7 3 5 7 5 9 7 7 5 5 7 5 7 5 7 5 7 9 5]


In [29]:
from numpy import random
random.seed(12)
x = random.choice([1,2,3], p=[0.2,0.3,0.5], size=(2,3))
random.seed(10)
y = random.choice([1,2,3], p=[0.2,0.3,0.5], size=(2,3))
random.seed(12)
z = random.choice([1,2,3], p=[0.2,0.3,0.5], size=(3,2))

print(x)
print()
print(y)
print()
print(z)

[[1 3 2]
 [3 1 3]]

[[3 1 3]
 [3 2 2]]

[[1 3]
 [2 3]
 [1 3]]
