In [37]:
from numpy import random
x = random.randint(100)
print(x)

y = random.rand()
print(y)

41
0.4476165714874084


In [33]:
from numpy import random
x = random.randint(100, size=(5))
print(x)

y = random.randint(100, size=(5,3))
print(y)

z = random.rand(5)
print(z)

[92 22  3 84 64]
[[26  3 92]
 [64 92 13]
 [10 51 32]
 [67 35  7]
 [81 74 81]]
[0.24570837 0.47875615 0.61269307 0.26623085 0.38010071]


In [41]:
from numpy import random
x = random.choice([1,2,3,4,5])
print(x)

y = random.choice([3,4,5,6], size=(3,5))
print(y)

3
[[3 5 6 4 3]
 [6 3 3 5 5]
 [6 6 5 5 6]]
