In [48]:
def add_expense(expenses, amount, category):
    expenses.append({'amount': amount, 'category': category})
    
def print_expenses(expenses):
    for expense in expenses:
        print(f'Amount: {expense["amount"]}, Category: {expense["category"]}')
    
def total_expenses(expenses):
    return sum(map(lambda expense: expense['amount'], expenses))
    
def filter_expenses_by_category(expenses, category):
    return filter(lambda expense: expense['category'] == category, expenses)
    

def main():
    expenses = []
    while True:
        print('\nExpense Tracker')
        print('1. Add an expense')
        print('2. List all expenses')
        print('3. Show total expenses')
        print('4. Filter expenses by category')
        print('5. Exit')
       
        choice = input('Enter your choice: ')

        if choice == '1':
            category = input('Enter category: ')
            amount = float(input('Enter amount: '))
            add_expense(expenses, amount, category)

        elif choice == '2':
            print('\nAll Expenses:')
            print_expenses(expenses)
    
        elif choice == '3':
            print('\nTotal Expenses: ', total_expenses(expenses))
    
        elif choice == '4':
            category = input('Enter category to filter: ')
            print(f'\nExpenses for {category}:')
            expenses_from_category = filter_expenses_by_category(expenses, category)
            print_expenses(expenses_from_category)
    
        elif choice == '5':
            print('Exiting the program.')
            break

main()


Expense Tracker
1. Add an expense
2. List all expenses
3. Show total expenses
4. Filter expenses by category
5. Exit


Enter your choice:  1
Enter amount:  20
Enter category:  Groceries



Expense Tracker
1. Add an expense
2. List all expenses
3. Show total expenses
4. Filter expenses by category
5. Exit


Enter your choice:  exit



Expense Tracker
1. Add an expense
2. List all expenses
3. Show total expenses
4. Filter expenses by category
5. Exit


Enter your choice:  Exit



Expense Tracker
1. Add an expense
2. List all expenses
3. Show total expenses
4. Filter expenses by category
5. Exit


Enter your choice:  5


Exiting the program.


In [6]:
import numpy as np

numbers = np.arange(1,21)
even_numbers = filter(lambda x:x%2==0, numbers)
print(list(even_numbers))

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]


In [8]:
import numpy as np

numbers = np.arange(1,21)
sum_of_numbers = sum(map(lambda x:x, numbers))
print(sum_of_numbers)

210


In [26]:
expense = {'item': 'groceries', 'amount': 5}

def get_amount(expense):
    return expense['amount']
get_amount(expense)

5

In [84]:
import numpy as np

arr = np.random.randint(0,100, size=(3,2,2,5))
print(arr)

[[[[50 10 82 31 45]
   [46 58  6 57 81]]

  [[16 71  2 37 90]
   [87 93  3 38  6]]]


 [[[ 7 71 93 53 31]
   [91 27 97 91  6]]

  [[93 20  4  9 96]
   [21 71 57  6  7]]]


 [[[76 55 28 97 81]
   [74 98  2 56 94]]

  [[92 16  4 74  2]
   [82 41 18 31 96]]]]
