In [13]:
#import numpy
import numpy as np

#converting datatypes 
arr = np.array([1.1, 2.2, 3.3])
newarr = arr.astype("i2")#defines the size too
print(newarr)
print("The datatype of the new array is:", newarr.dtype)

[1 2 3]
The datatype of the new array is: int16


In [29]:
import numpy as np

arr = np.array([-1, 0, 1])
newarr = arr.astype(bool)
print(newarr)
print("Zero is False")

[ True False  True]
Zero is False


In [45]:
#Copy vs View

import numpy as np

#Making changes to the array to see if the copy will be affected
arr = np.array([1,2,3,4])
newarr = arr.copy()
arr[0] = 42

print(arr)
print(newarr)
print("Copy is not affected by changes to the array")
print()

#Making changes to the array to see if the view will be affected 
arr2 = np.array([1,2,3,4])
newarr2 = arr2.view()
arr2[0] = 32

print(arr2)
print(newarr2)
print("View is affected by changes to the array")
print()

#Making changes to the view to see if the array will be affected
arr3 = np.array([1,2,3,4])
newarr3 = arr3.view()
newarr3[0] = 34

print(arr3)
print(newarr3)
print("Array is affected by changes to the view")

[42  2  3  4]
[1 2 3 4]
Copy is not affected by changes to the array

[32  2  3  4]
[32  2  3  4]
View is affected by changes to the array

[34  2  3  4]
[34  2  3  4]
Array is affected by changes to the view


In [63]:
#Checking if an array owns its data or not

import numpy as np

arr = np.array([1,2,3,4])

x = arr.copy()
y = arr.view()

print(x.base, "\n Copy owns the data")
print()
print(y.base, "\n View doesn't own the data")

None 
 Copy owns the data

[1 2 3 4] 
 View doesn't own the data


In [57]:
#Shape of an array

import numpy as np
arr = np.array([[1,2,3], [4,5,6]])
print(arr.shape, "\n Signifies the array has two dimensions. The first dimension has two elements and the second dimension has three elements.")
print()

arr2 = np.array([1,2,3,4], ndmin = 5)
print(arr2.shape)

(2, 3) 
Signifies the array has two dimensions. The first dimension has two elements and the second dimension has three elements.

(1, 1, 1, 1, 4)


In [73]:
#Reshaping arrays

import numpy as np

#reshape a 1d to 3d
arr = np.arange(1, 13)
newarr= arr.reshape(3,2,2)

print(arr)
print()
print(newarr)
print()
print(newarr.base, "\n Returns the original array so it's a view.")


[ 1  2  3  4  5  6  7  8  9 10 11 12]

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]

[ 1  2  3  4  5  6  7  8  9 10 11 12] 
 Returns the original array so it's a view.


In [87]:
#Unknown Array

import numpy as np

arr = np.arange(1, 9)
newarr = arr.reshape(2,2,-1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [93]:
#Flattening the array

import numpy as np
arr = np.array([[[1,2,3], [4,5,6], [7,8,9]]])
newarr = arr.reshape(-1)
print(arr)
print()
print(newarr, "\n Converts a multidimensional array to 1D")

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]

[1 2 3 4 5 6 7 8 9] 
 Converts a multidimensional array to 1D
