In [28]:
#Import libraries
import numpy as np 

#Test One
#create an all ones matrix
arr = np.ones([5,5], dtype = int)
print(arr) 

#modify the array
arr[1:4, 1:4] = np.zeros([3,3])
print(arr)

arr[2,2] = 9
print(arr)


[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [145]:
#Test Two
#create an array of numbers in a particular order
arr = np.arange(1, 31)
print(arr)

#reshape the array
arr = arr.reshape(6,5)
print(arr)

#index 'arr2'
arr2 = arr[2:4, 0:2]
print(arr2)

#modify 'arr2'
arr2 = np.array([31,32,33,34])
arr2 = arr2.reshape(2,2)
print(arr2)

arr[2:4, 0:2] = arr2
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
[[11 12]
 [16 17]]
[[31 32]
 [33 34]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [31 32 13 14 15]
 [33 34 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [173]:
#Test Three
#create an array of numbers in a particular order
arr = np.arange(1,31)
print(arr)

#reshape the array
arr = np.reshape(arr, (6,5))
print(arr)

#index 'arr2'
arr2 = arr[[0,1,2,3], [1,2,3,4]]
print(arr2)

#modify 'arr2'
arr2 = arr2 * 2
print(arr2)

#mask it back into 'arr'
arr[[0,1,2,3], [1,2,3,4]] = arr2
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
[ 2  8 14 20]
[ 4 16 28 40]
[[ 1  4  3  4  5]
 [ 6  7 16  9 10]
 [11 12 13 28 15]
 [16 17 18 19 40]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [229]:
#Test Four
#create an array with ints in order
arr = np.arange(1,51)
print(arr)

#reshape the array
arr = np.reshape(arr, (5, 10))
print(arr)

#index 'arr2'
arr2 = arr[[0,2,3], 1:8]
print(arr2)

#modify it again
arr2 = arr2 ** 2
print(arr2)

arr[[0, 2, 3], 1:8] = arr2
print(arr)

#modify 'arr2'
arr2 = np.full((3,7), 99)
print(arr2) 

arr[[0,2,3], 1:8] = arr2
print(arr)

#modify it again
arr2 = np.arange(41, 83, 2)
arr2 = np.reshape(arr2, (3,7))
print(arr2)

arr[[0,2,3], 1:8] = arr2
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]
[[ 2  3  4  5  6  7  8]
 [22 23 24 25 26 27 28]
 [32 33 34 35 36 37 38]]
[[   4    9   16   25   36   49   64]
 [ 484  529  576  625  676  729  784]
 [1024 1089 1156 1225 1296 1369 1444]]
[[   1    4    9   16   25   36   49   64    9   10]
 [  11   12   13   14   15   16   17   18   19   20]
 [  21  484  529  576  625  676  729  784   29   30]
 [  31 1024 1089 1156 1225 1296 1369 1444   39   40]
 [  41   42   43   44   45   46   47   48   49   50]]
[[99 99 99 99 99 99 99]
 [99 99 99 99 99 99 99]
 [99 99 99 99 99 99 99]]
[[ 1 99 99 99 99 99 99 99  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 99 99 99 99 99 99 99 29 30]
 [31 99 99 99 99 99 99 99 39 40]
 [41 42 43 44 45 46 4