In [1]:
import numpy as np
arr1 = np.arange(1,4)
arr2 = np.arange(4,7)

arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [13]:
import numpy as np
arr1 = np.arange(4,).reshape(2,2) + 1
arr2 = np.arange(4,).reshape(2,2) + 5

arr = np.concatenate((arr1, arr2), axis=1)#along rows
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [9]:
#Stacking
import numpy as np
arr1 = np.arange(3,) + 1
arr2 = np.arange(3,) + 4

arr = np.stack((arr1, arr2), axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [19]:
#Stacking along rows
import numpy as np
arr1 = np.arange(5,)+1
arr2 = np.arange(5,)+6

arr = np.hstack((arr1, arr2))
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [23]:
#Stacking along columns
import numpy as np
arr1 = np.arange(5,)+1
arr2 = np.arange(5,)+6

arr = np.vstack((arr1, arr2))
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [25]:
#Stacking along depth(height)
import numpy as np
arr1 = np.arange(3,)+1
arr2 = np.arange(3,)+4

arr = np.dstack((arr1, arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [45]:
import numpy as np
a = np.array([[1,2]])
b = np.array([[3,4]])
c = np.array([[5,6]])
d = np.array([[7,8]])

arr1 = np.block([[a,b,c,d]])
arr2 = np.block([[a,b], [c,d]])

print(arr1)
print()
print(arr2)

[[1 2 3 4 5 6 7 8]]

[[1 2 3 4]
 [5 6 7 8]]
