In [21]:
import numpy as np
arr = np.array([1,2,3,4,5,4,4])
x = np.where(arr == 4)
print(x)

arrEven = np.arange(11)
y = np.where(arrEven%2 == 0)
print(y)

arrOdd = np.arange(11)
z = np.where(arrOdd%2 == 1)
print(z)

(array([3, 5, 6], dtype=int64),)
(array([ 0,  2,  4,  6,  8, 10], dtype=int64),)
(array([1, 3, 5, 7, 9], dtype=int64),)


In [103]:
import numpy as np
arr = np.arange(5)+6
x = np.searchsorted(arr, 7)
print(x)

arr2 = np.random.randint(1,10,4)
print(arr2)
y = np.searchsorted(arr2, 7)
print(y)
z = np.searchsorted(arr2, 7, side='right')
print(z)

ax = np.searchsorted(arr, [6,7,8])
print(ax)

1
[7 9 5 9]
3
3
[0 1 2]
