In [17]:
import numpy as np
arr = np.random.randint(0,5,5)
print(arr)
print(np.sort(arr))

arrBool = np.array(["True", "False", "True", "False"])
print(np.sort(arrBool))

arrTwo = np.array([[3,0,1], [4,8,1]])
print(np.sort(arrTwo))

[2 3 0 3 3]
[0 2 3 3 3]
['False' 'False' 'True' 'True']
[[0 1 3]
 [1 4 8]]
